### ISSUE TITLE
Changed download mechanism from Geolite

### ISSUE THREAD

**Issue by patrick-abc** [diabl0/piwik-geoip2#15]
Geolite has changed the download mechanism for the free Geolite database. Since December, 30 for downloads you have to be a registred user. See: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Do you change the geoip2 Plugin to add credentials in settings?

**Comment by patrick-abc** [comment]
Ups sorry, Plugin is integrated in core. Problem already discussed here: https://github.com/matomo-org/matomo/issues/15308

**Comment by wolandtel** [comment]
@mattab it's not a good idea. I've changed download URL to my personal (with credentials) and don't expect it'll be changed to db-ip URL.
