### ISSUE TITLE
Location Provider: GeoIP (Php) is gone when piwik-geoip2 plugin is active

### ISSUE THREAD

**Issue by slawa-dev** [diabl0/piwik-geoip2#6]
After activating piwik-geoip2 plugin one of the default location providers: GeoIP (Php) is not there anymore.
See issue https://github.com/piwik/piwik/issues/11157

**Comment by slawa-dev** [comment]
@ahaenggli Thanks.

**Comment by diabl0** [comment]
Fixed, once again thanks to @ahaenggli
